@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTY3ODM1NDB9.myHCD2QoEUORJoqlN5wU-uFhEHMiNw4Nvyxx0cV3C70

### Get all assets
GET http://localhost:3000/assets.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Get asset by id
GET http://localhost:3000/assets/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

