@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTkxOTc0NDV9.IlG7Oi5kJwA3DywjNAkDjXgkmfF9_dmU8ae-jyjaZCA

### Get get baskets
GET http://localhost:3000/asset_baskets.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

