



@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTcxMjU4MTl9.iGbP-ugGjbvNrG9m31P9tUnQ0BiLEXggiJu55EWYuhE

### Get baskets
GET http://localhost:3000/baskets.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

