



@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTY3ODM1NDB9.myHCD2QoEUORJoqlN5wU-uFhEHMiNw4Nvyxx0cV3C70

### Get baskets
GET http://localhost:3000/baskets.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

