

 @jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTcxMjU4MTl9.iGbP-ugGjbvNrG9m31P9tUnQ0BiLEXggiJu55EWYuhE

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Thomas MTest",
  "email": "test3@test.com",
  "username": "test112334",
  "age": 15,
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "password"
}

#### Get User Info

GET http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

