

 @jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTkxOTc0NDV9.IlG7Oi5kJwA3DywjNAkDjXgkmfF9_dmU8ae-jyjaZCA

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Charlie Harned",
  "email": "charlie2@test.com",
  "username": "charlie harned",
  "age": 29,
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "charlie2@test.com",
  "password": "password"
}

#### Get User Info

GET http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Update User
PATCH http://localhost:3000/users.json
Content-type: application/json
Authorization: Bearer {{jwt}}

{
  "first_name": "Charlie",
  "last_name": "Harned",
  "username": "test543",
  "status": "active"
  
}

#### Deactivate User

DELETE http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

